name: Deploy

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev
    types:
      - labeled
  workflow_dispatch:

env:
  branch_name: ${{ github.head_ref || github.ref_name }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Publish Website to Cloudflare Pages
      uses: cloudflare/wrangler-action@v3
      with:
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: pages deploy ./dist --project-name=klang-dapp --branch=$branch_name